apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # labels of deployment resource
  labels:
    app: backend
    tier: backend
    project: expense
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
      version: blue

  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
        ersion: blue

    spec:
      containers:
        - name: backend
          image: peddireddylokesh/backend:1.0.0
---