apiVersion: v1
kind: Service
metadata:                 # this is all internal to the cluster
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
    version: green
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 

 